# Generated by Django 2.1.5 on 2019-10-14 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_no', models.CharField(max_length=100)),
                ('current_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='prime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('no_of_slot', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='parking',
            name='park_loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.prime'),
        ),
    ]
